name = "TrackingFloats"
uuid = "9b3335e5-bfd3-4ceb-9deb-1a1ba3ea6b86"
authors = ["JonasH <hanssonjonas96@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
